Merge 6.2.x into 7.0.x (#387)
* Add grails-app/conf/spring/resources.groovy as a default feature (#366)

* Add grails-app/conf/spring/resources.groovy as a default feature to align with pre Grails 6 versions

* Set "executable" flag on grailsw

* Update to grails wrapper 4.0.1 - includes update-wrapper command for Grails 6 (#375)

* prep for grails 6.2.1 release (#376)

* [skip ci] Release v6.2.1

* chore: Bump version to 6.2.2-SNAPSHOT

* update grails-core to 6.2.2-SNAPSHOT (#379)

* update grails-core 6.2.2-SNAPSHOT

* Use Java 11 in 6.2.x branch (#382)

* ci: Use Java 11 in 6.2.x branch

If native image is built with Java 17, application created with it will not be compatible with Java 11.

Error: LinkageError occurred while loading main class g621app.Application java.lang.UnsupportedClassVersionError: g621app/Application has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

* ci: graalvm +version -distribution

Test tip from https://github.com/graalvm/setup-graalvm/issues/105#issuecomment-2352562370

* ci: Disable OSX Arm Native CLI

Graalvm cannot build Java 11 OSX Arm Native Image

Error: Failed to download graalvm-ce-java11-darwin-aarch64-22.3.3. Are you sure version: '22.3.3' and java-version: '11' are correct?

* Include Geb/Selenium dependencies for MacOS Arch64 (#385)

* fix: Enable inclusion of Geb/Selenium deps for Macos Arch64

This was already enabled in another part of the code in
ad660a56e969855d7792e7ffdfed26fc58b2759c

It looks like this was missed.

* test: Temporarily disable integrationTest task in create-app specs

Due to an issue with the integrationTest task during the create-app tests, the task is being temporarily disabled. The tests fail with `org.openqa.selenium.SessionNotCreatedException`, which seems to be related to the inclusion of Geb/Selenium dependencies for `OperatingSystem.MACOS_ARCH64`.

The apps in the create-app tests are created with `OperatingSystem.MACOS_ARCH64` as the operating system parameter, but will fail also for other operating systems.

This issue was likely masked before commit 8675723e62df6d136d7af48d5c75d7728cbef871, when the Geb/Selenium dependencies were not included for MACOS_ARCH64. With the dependencies now included, the integrationTest task fails.

---------

Co-authored-by: Scott Murphy <scott@alwaysvip.com>
Co-authored-by: grails-build <grails-build@users.noreply.github.com>
Co-authored-by: Mattias Reichel <mattias.reichel@gmail.com>